name: Integration Tests
on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  integration_tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
#       - name: Pull Request Comment Trigger
#         uses: Khan/pull-request-comment-trigger@1.0.0
#         id: check
#         with:
#           trigger: '/test'
#           reaction: 'eyes'
#         env:
#           GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Check files
        run: ls
      - name: checkcontext
        uses: hmarr/debug-action@v2
      - name: Checkout merge cormit
        uses: actions/checkout@v3
        with:
          ref: "refs/pull/${{ github.event.issue.number }}/merge"
      - name: check updated files
        run: ls
